name: Github Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true
      sampleRepoLink:
        description: Link to the HyperExecute sample repo
        default: https://github.com/LambdaTest/testng-selenium-hyperexecute-sample
        required: true

jobs:
  HyperExecute-Selenium:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        id: testng
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone https://github.com/SparshKesari/testng-selenium-hyperexecute-sample-main
          echo "STEP 2) Download CLI and setting environment variables"
          cd testng-selenium-hyperexecute-sample-main
          curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
          export LT_USERNAME=sparshk
          export LT_ACCESS_KEY=2LL7kOYTDbOeSYc5Bgw8qw381iYInMvLCFs9WpCXVFR38CVyIo
          echo $LT_USERNAME
          echo $LT_ACCESS_KEY
          ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config yaml/win/testng_hyperexecute_autosplit_sample.yaml --download-artifacts --download-report
